apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      nodePort: 30010
      port: 8500